@echo off
rem Switches the project in this folder back to ONLINE mode: nuget.org plus
rem the local flat feed "packages" as a cache. A backed-up custom config
rem (nuget.online.config) is restored with priority; a custom config that was
rem never replaced is left untouched.
rem Portable: copy this script into any project folder and run it.
setlocal EnableExtensions
cd /d "%~dp0"

echo Switching to ONLINE NuGet (nuget.org + local cache)...

rem 1 = current nuget.config was generated by these scripts (LocalOffline/LocalCache marker)
set "GENERATED=0"
if exist nuget.config (
    findstr /C:"LocalOffline" nuget.config >nul 2>&1 && set "GENERATED=1"
    findstr /C:"LocalCache" nuget.config >nul 2>&1 && set "GENERATED=1"
)

rem Replace only script-generated configs; a custom config is never touched
if "%GENERATED%"=="1" del /q nuget.config

if exist nuget.online.config ren nuget.online.config nuget.config

if not exist nuget.config (
    echo Creating online nuget.config with nuget.org + local cache...
    > nuget.config echo ^<?xml version="1.0" encoding="utf-8"?^>
    >> nuget.config echo ^<configuration^>
    >> nuget.config echo   ^<packageSources^>
    if exist packages (
        >> nuget.config echo     ^<add key="LocalCache" value="packages" /^>
    )
    >> nuget.config echo     ^<add key="nuget.org" value="https://api.nuget.org/v3/index.json" /^>
    >> nuget.config echo   ^</packageSources^>
    >> nuget.config echo ^</configuration^>
)

echo Done. Restore now uses nuget.org plus the local "packages" cache.
endlocal
