@echo off
rem Switches the project in this folder to OFFLINE mode: NuGet restore uses
rem only the local flat feed "packages". A custom nuget.config is backed up
rem to nuget.online.config and is restored by switch_to_online_packages.cmd.
rem Portable: copy this script into any project folder and run it.
setlocal EnableExtensions
cd /d "%~dp0"

echo Switching to LOCAL packages only (offline)...

rem 1 = current nuget.config was generated by these scripts (LocalOffline/LocalCache marker)
set "GENERATED=0"
if exist nuget.config (
    findstr /C:"LocalOffline" nuget.config >nul 2>&1 && set "GENERATED=1"
    findstr /C:"LocalCache" nuget.config >nul 2>&1 && set "GENERATED=1"
)

rem Back up a custom config only when the current one is not script-generated;
rem a stale backup is replaced so the newest custom config is never lost
if "%GENERATED%"=="0" (
    if exist nuget.online.config del /q nuget.online.config
    if exist nuget.config ren nuget.config nuget.online.config
)

> nuget.config echo ^<?xml version="1.0" encoding="utf-8"?^>
>> nuget.config echo ^<configuration^>
>> nuget.config echo   ^<packageSources^>
>> nuget.config echo     ^<clear /^>
>> nuget.config echo     ^<add key="LocalOffline" value="packages" /^>
>> nuget.config echo   ^</packageSources^>
>> nuget.config echo ^</configuration^>

rem Fast local sync: copy the dependency closure from the machine global cache
rem (needs a completed restore; otherwise run download_local_packages.cmd first)
powershell -NoProfile -ExecutionPolicy Bypass -Command "$files = @(); for ($i = 0; $i -lt 3 -and -not $files; $i++) { $files = @([System.IO.Directory]::GetFiles((Get-Location).Path, 'project.assets.json', [System.IO.SearchOption]::AllDirectories) | Where-Object { $_ -match '\\obj\\' }); if (-not $files) { Start-Sleep -Seconds 2 } }; $paths = @($files | ForEach-Object { (Get-Content $_ -Raw | ConvertFrom-Json).libraries.PSObject.Properties | Where-Object { $_.Value.type -eq 'package' } | ForEach-Object { $_.Value.path } } | Sort-Object -Unique); if (-not $paths) { Write-Host 'NOTE: no project.assets.json found - run download_local_packages.cmd first to fill the feed.'; exit 0 }; $src = Join-Path $env:USERPROFILE '.nuget\packages'; New-Item -ItemType Directory -Force -Path packages | Out-Null; $ok = 0; $miss = @(); foreach ($p in $paths) { $ver = Split-Path $p -Leaf; $id = Split-Path (Split-Path $p -Parent) -Leaf; $nupkg = $id + '.' + $ver + '.nupkg'; $sdir = Join-Path $src $p; if (Test-Path (Join-Path $sdir $nupkg)) { robocopy $sdir packages $nupkg /njh /njs /ndl /nfl > $null; if ($LASTEXITCODE -lt 8) { $ok++ } else { $miss += $p } } else { $miss += $p } }; Write-Host ('Local feed: ' + $ok + ' of ' + $paths.Count + ' packages synced from the global cache.'); if ($miss) { Write-Host ('NOTE: not in the global cache - run download_local_packages.cmd to fetch: ' + ($miss -join ', ')) }"

echo Done. Restore now uses only the local "packages" feed.
endlocal
