<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>DataShield.GUI</RootNamespace>
    <AssemblyName>DataShield.GUI</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <AssemblyTitle>DataShield.GUI</AssemblyTitle>
    <Version>3.0</Version>
    <AssemblyVersion>3.0.0.0</AssemblyVersion>
    <FileVersion>3.0.0.0</FileVersion>
    <Company>Artem Drobanov</Company>
    <Authors>Artem Drobanov</Authors>
    <Copyright>Copyright (c) 2026 Artem Drobanov</Copyright>
    <Description>DataShield.GUI - Avalonia interface / FEC codec (Reed-Solomon GF(16), Cauchy matrix)</Description>
    <Product>DataShield</Product>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <NeutralLanguage>en</NeutralLanguage>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.20" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.20" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.20" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.20" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataShield.Codec\DataShield.Codec.csproj" />
  </ItemGroup>

</Project>
