//------------------------------------------------------------------------------
// <auto-generated>
//     Класс типизированного доступа к ресурсам локализации интерфейса.
//     Поддерживается вручную: при добавлении ключа в UiStrings.resx
//     и UiStrings.ru.resx добавить одноимённое свойство сюда.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataShield.Gui
{
    using System;
    using System.CodeDom.Compiler;
    using System.Globalization;
    using System.Resources;
    using System.Runtime.CompilerServices;

    /// <summary>
    /// Локализованные строки интерфейса и файловых отчётов.
    /// Нейтральные ресурсы (UiStrings.resx) — английские; русский язык —
    /// в сателлитных ресурсах (UiStrings.ru.resx). Язык задаётся через
    /// <see cref="Culture"/> (см. <see cref="LanguageManager"/>).
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    public sealed class UiStrings
    {
        private static ResourceManager _resourceMan;

        private static CultureInfo _resourceCulture;

        private UiStrings()
        {
        }

        /// <summary>Общий экземпляр ResourceManager для ресурсов UiStrings.</summary>
        public static ResourceManager ResourceManager
        {
            get
            {
                if (_resourceMan is null)
                {
                    var temp = new ResourceManager(
                        "DataShield.Gui.UiStrings",
                        typeof(UiStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        /// <summary>Язык выборки строк; null — CurrentUICulture потока.</summary>
        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        /// <summary>«Режим:»</summary>
        public static string ModeLabel => ResourceManager.GetString("ModeLabel", _resourceCulture);

        /// <summary>«Кодирование».</summary>
        public static string ModeEncode => ResourceManager.GetString("ModeEncode", _resourceCulture);

        /// <summary>«Декодирование».</summary>
        public static string ModeDecode => ResourceManager.GetString("ModeDecode", _resourceCulture);

        /// <summary>«Язык:»</summary>
        public static string LanguageLabel => ResourceManager.GetString("LanguageLabel", _resourceCulture);

        /// <summary>«English» (нативное название).</summary>
        public static string LangEnglish => ResourceManager.GetString("LangEnglish", _resourceCulture);

        /// <summary>«Русский» (нативное название).</summary>
        public static string LangRussian => ResourceManager.GetString("LangRussian", _resourceCulture);

        /// <summary>«Входной файл:»</summary>
        public static string InputFileLabel => ResourceManager.GetString("InputFileLabel", _resourceCulture);

        /// <summary>«Выходной файл:»</summary>
        public static string OutputFileLabel => ResourceManager.GetString("OutputFileLabel", _resourceCulture);

        /// <summary>Флажок «имя выходного файла — из заголовка потока» (декодирование).</summary>
        public static string UseSlotName => ResourceManager.GetString("UseSlotName", _resourceCulture);

        /// <summary>«Обзор...»</summary>
        public static string BrowseButton => ResourceManager.GetString("BrowseButton", _resourceCulture);

        /// <summary>«Формат:»</summary>
        public static string FormatLabel => ResourceManager.GetString("FormatLabel", _resourceCulture);

        /// <summary>Заголовок группы избыточности.</summary>
        public static string RedundancyHeader => ResourceManager.GetString("RedundancyHeader", _resourceCulture);

        /// <summary>Подпись ползунка ECC.</summary>
        public static string EccLabel => ResourceManager.GetString("EccLabel", _resourceCulture);

        /// <summary>Подпись ползунка заголовков.</summary>
        public static string HeadersLabel => ResourceManager.GetString("HeadersLabel", _resourceCulture);

        /// <summary>Кнопка запуска.</summary>
        public static string RunButton => ResourceManager.GetString("RunButton", _resourceCulture);

        /// <summary>Кнопка отмены.</summary>
        public static string CancelButton => ResourceManager.GetString("CancelButton", _resourceCulture);

        /// <summary>Заголовок блока прогресса.</summary>
        public static string ProgressCaption => ResourceManager.GetString("ProgressCaption", _resourceCulture);

        /// <summary>Заголовок блока результата.</summary>
        public static string ResultCaption => ResourceManager.GetString("ResultCaption", _resourceCulture);

        /// <summary>Заголовок блока карты валидности.</summary>
        public static string MapCaption => ResourceManager.GetString("MapCaption", _resourceCulture);

        /// <summary>Заголовок диалога выбора входного файла (кодирование).</summary>
        public static string InputDialogEncodeTitle => ResourceManager.GetString("InputDialogEncodeTitle", _resourceCulture);

        /// <summary>Заголовок диалога выбора входного файла (декодирование).</summary>
        public static string InputDialogDecodeTitle => ResourceManager.GetString("InputDialogDecodeTitle", _resourceCulture);

        /// <summary>Фильтр «Все файлы».</summary>
        public static string FilterAllFiles => ResourceManager.GetString("FilterAllFiles", _resourceCulture);

        /// <summary>Фильтр диалога выбора FEC-потока.</summary>
        public static string FilterDecodeStream => ResourceManager.GetString("FilterDecodeStream", _resourceCulture);

        /// <summary>Заголовок диалога сохранения.</summary>
        public static string OutputDialogTitle => ResourceManager.GetString("OutputDialogTitle", _resourceCulture);

        /// <summary>Фильтр диалога сохранения FEC-потока.</summary>
        public static string FilterEncodeOutput => ResourceManager.GetString("FilterEncodeOutput", _resourceCulture);

        /// <summary>Имя выходного файла по умолчанию (кодирование).</summary>
        public static string DefaultOutputName => ResourceManager.GetString("DefaultOutputName", _resourceCulture);

        /// <summary>Имя выходного файла по умолчанию (декодирование).</summary>
        public static string DefaultDecodeName => ResourceManager.GetString("DefaultDecodeName", _resourceCulture);

        /// <summary>Фаза «Подготовка...».</summary>
        public static string PhasePreparing => ResourceManager.GetString("PhasePreparing", _resourceCulture);

        /// <summary>Статус «Операция отменена.»</summary>
        public static string StatusCancelled => ResourceManager.GetString("StatusCancelled", _resourceCulture);

        /// <summary>Статус «Отмена...».</summary>
        public static string StatusCancelling => ResourceManager.GetString("StatusCancelling", _resourceCulture);

        /// <summary>«Ошибка: {0}».</summary>
        public static string StatusErrorFormat => ResourceManager.GetString("StatusErrorFormat", _resourceCulture);

        /// <summary>Статус «Завершено.»</summary>
        public static string StatusCompleted => ResourceManager.GetString("StatusCompleted", _resourceCulture);

        /// <summary>«Сначала выберите входной файл.»</summary>
        public static string StatusNoInput => ResourceManager.GetString("StatusNoInput", _resourceCulture);

        /// <summary>«Кодирование: {0}».</summary>
        public static string StatusEncodingFormat => ResourceManager.GetString("StatusEncodingFormat", _resourceCulture);

        /// <summary>«Декодирование: {0}».</summary>
        public static string StatusDecodingFormat => ResourceManager.GetString("StatusDecodingFormat", _resourceCulture);

        /// <summary>«Готово: {0} Б -> {1} пакетов».</summary>
        public static string EncodeDoneFormat => ResourceManager.GetString("EncodeDoneFormat", _resourceCulture);

        /// <summary>«Готово: {0} Б -> {1}».</summary>
        public static string DecodeDoneFormat => ResourceManager.GetString("DecodeDoneFormat", _resourceCulture);

        /// <summary>Ошибка: заголовки не обнаружены.</summary>
        public static string NoHeadersError => ResourceManager.GetString("NoHeadersError", _resourceCulture);

        /// <summary>Ошибка: нет данных для сборки.</summary>
        public static string NoDataError => ResourceManager.GetString("NoDataError", _resourceCulture);

        /// <summary>«Не удалось собрать: ... ECC (M={0}) ...».</summary>
        public static string FailWithEccFormat => ResourceManager.GetString("FailWithEccFormat", _resourceCulture);

        /// <summary>«Не удалось собрать (есть пропуски, ECC в потоке нет).»</summary>
        public static string FailNoEcc => ResourceManager.GetString("FailNoEcc", _resourceCulture);

        /// <summary>Метка строки результата: формат входа.</summary>
        public static string RInputFormat => ResourceManager.GetString("RInputFormat", _resourceCulture);

        /// <summary>Метка строки результата: формат вывода.</summary>
        public static string ROutputFormat => ResourceManager.GetString("ROutputFormat", _resourceCulture);

        /// <summary>Метка строки результата: имя файла.</summary>
        public static string RFileName => ResourceManager.GetString("RFileName", _resourceCulture);

        /// <summary>Метка строки результата: исходный размер.</summary>
        public static string RSourceSize => ResourceManager.GetString("RSourceSize", _resourceCulture);

        /// <summary>Метка строки результата: размер.</summary>
        public static string RSize => ResourceManager.GetString("RSize", _resourceCulture);

        /// <summary>Метка строки результата: SHA-256.</summary>
        public static string RSha256 => ResourceManager.GetString("RSha256", _resourceCulture);

        /// <summary>Метка строки результата: число data-томов.</summary>
        public static string RDataVolumes => ResourceManager.GetString("RDataVolumes", _resourceCulture);

        /// <summary>Метка строки результата: число ECC-томов.</summary>
        public static string REccVolumes => ResourceManager.GetString("REccVolumes", _resourceCulture);

        /// <summary>Метка строки результата: всего пакетов.</summary>
        public static string RTotalPackets => ResourceManager.GetString("RTotalPackets", _resourceCulture);

        /// <summary>Метка строки результата: копий заголовка.</summary>
        public static string RHeaderCopies => ResourceManager.GetString("RHeaderCopies", _resourceCulture);

        /// <summary>Метка строки результата: заголовки.</summary>
        public static string RHeaders => ResourceManager.GetString("RHeaders", _resourceCulture);

        /// <summary>Метка строки результата: накладные расходы.</summary>
        public static string ROverhead => ResourceManager.GetString("ROverhead", _resourceCulture);

        /// <summary>Метка строки результата: выходной файл.</summary>
        public static string ROutputFile => ResourceManager.GetString("ROutputFile", _resourceCulture);

        /// <summary>Метка строки результата: файл карты.</summary>
        public static string RMapFile => ResourceManager.GetString("RMapFile", _resourceCulture);

        /// <summary>Метка строки результата: секторы.</summary>
        public static string RSectors => ResourceManager.GetString("RSectors", _resourceCulture);

        /// <summary>Единица измерения «байт».</summary>
        public static string BytesUnit => ResourceManager.GetString("BytesUnit", _resourceCulture);

        /// <summary>Слово «покрытие» для строки секторов.</summary>
        public static string RCoverage => ResourceManager.GetString("RCoverage", _resourceCulture);

        /// <summary>«принято {0} копий».</summary>
        public static string HeadersCopiesReceivedFormat => ResourceManager.GetString("HeadersCopiesReceivedFormat", _resourceCulture);

        /// <summary>Заголовок MAP-отчёта.</summary>
        public static string MapReportTitle => ResourceManager.GetString("MapReportTitle", _resourceCulture);

        /// <summary>Метка MAP-отчёта: заголовков.</summary>
        public static string MapHeadersCount => ResourceManager.GetString("MapHeadersCount", _resourceCulture);

        /// <summary>Метка MAP-отчёта: всего.</summary>
        public static string MapTotal => ResourceManager.GetString("MapTotal", _resourceCulture);

        /// <summary>Метка MAP-отчёта: принято.</summary>
        public static string MapPresent => ResourceManager.GetString("MapPresent", _resourceCulture);

        /// <summary>Метка MAP-отчёта: пропущено.</summary>
        public static string MapMissing => ResourceManager.GetString("MapMissing", _resourceCulture);

        /// <summary>Метка MAP-отчёта: покрытие.</summary>
        public static string MapCoverage => ResourceManager.GetString("MapCoverage", _resourceCulture);

        /// <summary>Легенда MAP-отчёта.</summary>
        public static string MapLegend => ResourceManager.GetString("MapLegend", _resourceCulture);

        /// <summary>Легенда мини-карты: данные (зелёный).</summary>
        public static string MapLegendData => ResourceManager.GetString("MapLegendData", _resourceCulture);

        /// <summary>Легенда мини-карты: ECC-том (синий).</summary>
        public static string MapLegendEcc => ResourceManager.GetString("MapLegendEcc", _resourceCulture);

        /// <summary>Легенда мини-карты: пропущен (красный).</summary>
        public static string MapLegendMissing => ResourceManager.GetString("MapLegendMissing", _resourceCulture);

        /// <summary>Легенда мини-карты: коллизия версий (жёлтый).</summary>
        public static string MapLegendCollision => ResourceManager.GetString("MapLegendCollision", _resourceCulture);

        /// <summary>Плейсхолдер пустой карты.</summary>
        public static string MapEmpty => ResourceManager.GetString("MapEmpty", _resourceCulture);
    }
}
